# Generated by Django 2.2.1 on 2020-03-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilliyHisob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('year_2010', models.CharField(max_length=15)),
                ('year_2011', models.CharField(max_length=15)),
                ('year_2012', models.CharField(max_length=15)),
                ('year_2013', models.CharField(max_length=15)),
                ('year_2014', models.CharField(max_length=15)),
                ('year_2015', models.CharField(max_length=15)),
                ('year_2016', models.CharField(max_length=15)),
                ('year_2017', models.CharField(max_length=15)),
                ('year_2018', models.CharField(max_length=15)),
            ],
        ),
    ]
